### ISSUE TITLE
Some creatures from another mods doesn't work

### ISSUE THREAD

**Issue by BearInBag** [joshiejack/Piscary#1]
I had tried add several mobs to Hatchery via datapack, but part of them doesn't work, all these mobs have bucket
[hatchery.txt](https://github.com/Harvest-Festival/Piscary/files/6728047/hatchery.txt)
And from these list works only
bettas:betta_fish, upgrade_aquatic:perch, fins:blu_wee, fins:pea_wee, fins:banded_redback_shrimp, fins:teal_arrowfish, fins:swamp_mucker, fins:flatback_sucker, fins:high_finned_blue, fins:phantom_nudibranch, fins:ornate_bugfish, fins:wee_wee, unnamedanimalmod:flashlight_fish, unnamedanimalmod:elephantnose_fish, unnamedanimalmod:black_diamond_stingray, unnamedanimalmod:rocket_killifish, unnamedanimalmod:leafy_seadragon, unnamedanimalmod:spotted_garden_eel, unnamedanimalmod:mudskipper
Also some fishes float on the side in hatchery

**Comment by joshiejack** [comment]
I'm going to guess while they have a bucket they don't use the vanilla one but I will take a look in to it. And yeah some fish will probably float on their side it depends on their model. I can add a rotation field to the hatchery file to help solve that.

**Comment by joshiejack** [comment]
Just had a look at betteranimalsplus and yeah they use a custom item instead of the fish bucket system already in minecraft. I think the easiest thing will be for me to have you pass in the item as well so any item will work. Wasn't expecting people to not use the fish bucket item for their fish buckets. So didn't want to do that but looks like I'll have to.

**Comment by WACriminalG2** [comment]
For what it's worth, that sounds like it will make the mod way, WAY more extensible for pack devs anyway. Silver linings?
